"""
Runs continuously: RL brain → rewrites Config.lua → Rojo syncs → Studio hot-reloads.
"""
import time, random, sys
from pathlib import Path

ROOT       = Path(__file__).parent
CONFIG_LUA = ROOT / "roblox_project/src/shared/Config.lua"

GAME_TYPES = ["OBBY","HORROR","PHYSICS","SURVIVAL","TYCOON","SIMULATOR","GTA_STYLE"]

def write_config(diff, game_type=None):
    gt = game_type or random.choice(GAME_TYPES)
    CONFIG_LUA.write_text(f"""
-- AUTO-GENERATED by config_bus.py — DO NOT EDIT MANUALLY
local Config = {{
    Difficulty        = {diff:.3f},
    Length            = {int(20 + diff * 15)},
    PlatformGap       = {max(2.5, 6.0 - diff):.2f},
    HazardChance      = {min(0.8, 0.2 + diff * 0.3):.3f},
    CheckpointSpacing = {max(4, 12 - int(diff * 2))},
    GameType          = "{gt}",
    Monetization      = {min(2.0, 0.8 + diff * 0.3):.3f},
}}
return Config
""")
    print(f"📝 config → diff={diff:.2f} type={gt}")

def rl_loop():
    diff = 1.0
    while True:
        diff += 0.02 if diff < 2.0 else -0.05
        diff = max(0.5, min(3.0, diff))
        write_config(diff)
        time.sleep(5)

if __name__ == "__main__":
    print("🧠 Config bus started — Ctrl+C to stop")
    rl_loop()
