#!/usr/bin/env bash
set -e

PLUGIN="$PWD/sellable_plugins/AIObbyGeneratorPro.lua"

if [ ! -f "$PLUGIN" ]; then
  echo "ERROR: Missing $PLUGIN"
  exit 1
fi

cp "$PLUGIN" "$PLUGIN.bak_export_presets"

python3 - "$PLUGIN" <<'PY'
from pathlib import Path
import sys

p = Path(sys.argv[1])
code = p.read_text(encoding="utf-8", errors="ignore")

insert = r'''

local PresetConfigs = {
	Easy = {
		ThemeName = "Neon",
		Difficulty = "Easy",
		Stages = 40,
		HazardDensity = "Low",
		Monetization = false,
	},
	Viral = {
		ThemeName = "Cyber",
		Difficulty = "Normal",
		Stages = 120,
		HazardDensity = "Medium",
		Monetization = true,
	},
	Hardcore = {
		ThemeName = "Lava",
		Difficulty = "Insane",
		Stages = 160,
		HazardDensity = "High",
		Monetization = true,
	},
	Monetized = {
		ThemeName = "Toxic",
		Difficulty = "Hard",
		Stages = 120,
		HazardDensity = "High",
		Monetization = true,
	},
}

local function applyPreset(name)
	local preset = PresetConfigs[name]
	if not preset then return end

	Config.ThemeName = preset.ThemeName
	Config.Difficulty = preset.Difficulty
	Config.Stages = preset.Stages
	Config.HazardDensity = preset.HazardDensity
	Config.Monetization = preset.Monetization

	applyTheme(Config.ThemeName)
end

local function exportBuildReport()
	local report = table.concat({
		"AI OBBY GENERATOR PRO - BUILD REPORT",
		"",
		"Theme: " .. tostring(Config.ThemeName),
		"Difficulty: " .. tostring(Config.Difficulty),
		"Stages: " .. tostring(Config.Stages),
		"Hazard Density: " .. tostring(Config.HazardDensity),
		"Monetization Hooks: " .. tostring(Config.Monetization),
		"",
		"Generated Systems:",
		"- Checkpoints",
		"- Coins",
		"- XP / levels",
		"- Daily reward",
		"- Upgrade shop",
		"- Shield protection",
		"- Jump / speed / shield boosters",
		"- Lava, spinners, lasers, crushers",
		"- Boss stage",
		"- Finish rewards",
		"",
		"Creator Polish Checklist:",
		"1. Test full course in Play mode.",
		"2. Replace placeholder colors/materials with branded art.",
		"3. Add thumbnails and icons.",
		"4. Configure gamepasses/dev products manually in Roblox Creator Dashboard.",
		"5. Add sound effects/music.",
		"6. Publish private test, then invite testers.",
		"7. Tune rewards after first playtest.",
		"",
		"Recommended Monetization:",
		"- 2x Coins gamepass",
		"- VIP trail/aura",
		"- Skip stage developer product",
		"- Revive developer product",
		"- Daily reward streak booster",
		"",
		"Generated by AI Obby Generator Pro."
	}, "\n")

	local existing = S.ReplicatedStorage:FindFirstChild(PREFIX .. "BuildReport")
	if existing then existing:Destroy() end

	local value = Instance.new("StringValue")
	value.Name = PREFIX .. "BuildReport"
	value.Value = report
	value.Parent = S.ReplicatedStorage

	warn("AI Obby Pro build report exported to ReplicatedStorage > " .. value.Name)
end
'''

if "local PresetConfigs =" not in code:
    marker = "local panelWidget"
    code = code.replace(marker, insert + "\n" + marker)

# Expand widget height
code = code.replace(
'''330,
		430,
		300,
		360''',
'''360,
		560,
		320,
		480'''
)

# Insert preset/export controls before generate button in panel
old = r'''
	local generate = Instance.new("TextButton")
	generate.Size = UDim2.new(.5,-15,0,38)
	generate.Position = UDim2.new(0,10,1,-48)
'''

new = r'''
	local presetLabel = Instance.new("TextLabel")
	presetLabel.Size = UDim2.new(1,-20,0,18)
	presetLabel.Position = UDim2.fromOffset(10,372)
	presetLabel.BackgroundTransparency = 1
	presetLabel.Text = "Presets"
	presetLabel.Font = Enum.Font.GothamBold
	presetLabel.TextSize = 12
	presetLabel.TextColor3 = Color3.fromRGB(210,220,240)
	presetLabel.TextXAlignment = Enum.TextXAlignment.Left
	presetLabel.Parent = root

	local presetNames = {"Easy", "Viral", "Hardcore", "Monetized"}
	for i, presetName in ipairs(presetNames) do
		local b = Instance.new("TextButton")
		b.Size = UDim2.new(0.5,-15,0,28)
		b.Position = UDim2.fromOffset(i % 2 == 1 and 10 or 180, 394 + math.floor((i-1)/2) * 34)
		b.BackgroundColor3 = Theme.Secondary
		b.BorderSizePixel = 0
		b.Text = presetName
		b.Font = Enum.Font.GothamBold
		b.TextSize = 13
		b.TextColor3 = Color3.new(1,1,1)
		b.Parent = root
		Instance.new("UICorner", b).CornerRadius = UDim.new(0,8)

		b.MouseButton1Click:Connect(function()
			applyPreset(presetName)
		end)
	end

	local export = Instance.new("TextButton")
	export.Size = UDim2.new(1,-20,0,32)
	export.Position = UDim2.fromOffset(10,466)
	export.BackgroundColor3 = Theme.Accent
	export.BorderSizePixel = 0
	export.Text = "EXPORT BUILD REPORT"
	export.Font = Enum.Font.GothamBlack
	export.TextSize = 14
	export.TextColor3 = Color3.new(1,1,1)
	export.Parent = root
	Instance.new("UICorner", export).CornerRadius = UDim.new(0,10)
	export.MouseButton1Click:Connect(exportBuildReport)

	local generate = Instance.new("TextButton")
	generate.Size = UDim2.new(.5,-15,0,38)
	generate.Position = UDim2.new(0,10,1,-48)
'''

code = code.replace(old, new)

p.write_text(code, encoding="utf-8")
print("✅ Added export notes + presets:", p)
PY

echo "✅ Patched AI Obby Pro export notes + presets"
echo "Backup: $PLUGIN.bak_export_presets"
