apiVersion: apps/v1
kind: Deployment
metadata:
  name: obby-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: obby-worker
  template:
    metadata:
      labels:
        app: obby-worker
    spec:
      containers:
      - name: worker
        image: obby-worker:latest
        env:
        - name: REDIS_HOST
          value: redis
