apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-factory-ingress
spec:
  rules:
    - host: gamefactory.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-api
                port:
                  number: 80
