import test from 'node:test';
import assert from 'node:assert/strict';
import {createPuzzle,act,nextHint,undo,restorePuzzle,connected} from '../../echo_life/v44/puzzles.js';
import {Simulation,relayPosition} from '../../echo_life/v44/simulation.js';
import {Checkpoint} from '../../echo_life/v44/checkpoint.js';
import {isSolid,clearLine} from '../../echo_life/v42/world.js';
function solve(p){for(let n=0;n<100&&!p.solved;n++){const h=nextHint(p);assert.notEqual(h.index,null,JSON.stringify(p));act(p,h.index);}assert(p.solved);}
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};};
test('128 generated puzzles are initially unsolved and solvable through hints',()=>{for(let n=0;n<128;n++){const p=createPuzzle(n);assert(!p.solved);if(p.type==='pipes')assert(!connected(p.cells));solve(p);}});
test('circuit layouts turn and light grids vary',()=>{assert.notDeepEqual(createPuzzle(0).solution,createPuzzle(4).solution);assert.notDeepEqual(createPuzzle(4).solution,createPuzzle(8).solution);assert.notDeepEqual(createPuzzle(1).cells,createPuzzle(5).cells);});
test('undo reverses coupled dials, lights, circuit rotations and order choices',()=>{for(let n=0;n<4;n++){const p=createPuzzle(n),before=JSON.stringify({cells:p.cells,chosen:p.chosen});act(p,0);assert(undo(p));assert.equal(JSON.stringify({cells:p.cells,chosen:p.chosen}),before);assert.equal(p.moves,0);assert(!undo(p));}const p=createPuzzle(3);solve(p);assert(!undo(p));});
test('undo history bounded and invalid actions leave moves unchanged',()=>{const p=createPuzzle(3);for(let i=0;i<110;i++){act(p,0);if(p.solved)break;}assert(p.history.length<=50);const q=createPuzzle(0);for(const i of [-1,9,0.5,NaN])assert(!act(q,i));assert.equal(q.moves,0);});
test('relay locations and connecting streets avoid city solids',()=>{for(let n=0;n<300;n++){const p=relayPosition(n);assert(!isSolid(p.x,p.y,15));if(n){const a=relayPosition(n-1),corner=p.y>a.y&&p.x-a.x<100?{x:p.x,y:a.y}:{x:a.x,y:p.y};assert(clearLine(a,corner,15));assert(clearLine(corner,p,15));}}});
test('checkpoint preserves puzzle moves, loadout, rewards and journal, no repeat rewards',()=>{const s=new Simulation(44),store=new Checkpoint(memory());s.player.x=s.relay.x;s.player.y=s.relay.y;act(s.relay.puzzle,0);store.save(s);const loaded=new Simulation(3);assert(store.restore(loaded));assert.deepEqual(loaded.relay.puzzle.cells,s.relay.puzzle.cells);assert.equal(loaded.relay.puzzle.moves,1);
 for(let j=0;j<100&&!s.relay.solved;j++){const h=nextHint(s.relay.puzzle);s.solveAction(h.index);}assert.equal(s.relays,1);store.save(s);assert(store.restore(loaded));assert.equal(loaded.relays,1);assert.equal(loaded.score,500);assert.equal(loaded.player.cash,200);assert.equal(loaded.journal.length,1);assert.equal(loaded.relay.puzzle.type,'lights');assert(!loaded.relay.solved);store.clear();assert.equal(store.read(),null);});
test('blocked, corrupted and invalid saves never prevent play',()=>{assert.equal(new Checkpoint({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}}).read(),null);const m=memory(),c=new Checkpoint(m);m.setItem('echo-life-v44-run','{bad');assert.equal(c.read(),null);const s=new Simulation(44);c.save(s);const data=JSON.parse(m.getItem('echo-life-v44-run'));data.player.x=250;data.player.y=250;m.setItem('echo-life-v44-run',JSON.stringify(data));assert.equal(c.read(),null);assert.equal(c.restore(s),false);});
test('restored puzzles reject illegal pipe shapes and retain safe defaults',()=>{const p=restorePuzzle(0,{type:'pipes',cells:Array(9).fill(15),moves:2});assert.deepEqual(p.cells,createPuzzle(0).cells);const q=restorePuzzle(2,{type:'order',chosen:[1,1],moves:2});assert.deepEqual(q.chosen,[]);});
test('restored movement and upgrades remain available after checkpoint',()=>{const s=new Simulation(44);s.upgrades.speed=2;s.upgrades.shield=3;s.player.maxShield=71;s.player.shield=71;s.weaponIndex=2;s.player.mag=12;s.medkits=3;const c=new Checkpoint(memory());c.save(s);const t=new Simulation(1);assert(c.restore(t));assert.equal(t.player.maxShield,71);assert.equal(t.weapon.id,'lance');assert.equal(t.medkits,3);t.update(1/60,{mx:1});assert(t.player.x>90);});
