from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from datetime import datetime, timezone

app = FastAPI(title="Game Factory SaaS API")

PLANS = {
    "free": {
        "stage_limit": 20,
        "themes": ["Candy", "Lava"],
        "exports_per_month": 3,
        "monetization": False,
    },
    "starter": {
        "stage_limit": 100,
        "themes": ["Candy", "Lava", "Cyber"],
        "exports_per_month": 25,
        "monetization": True,
    },
    "pro": {
        "stage_limit": 200,
        "themes": ["Candy", "Lava", "Cyber", "Space", "Jungle", "Horror"],
        "exports_per_month": 250,
        "monetization": True,
    },
    "studio": {
        "stage_limit": 500,
        "themes": ["Candy", "Lava", "Cyber", "Space", "Jungle", "Horror"],
        "exports_per_month": 2000,
        "monetization": True,
    },
}

LICENSES = {
    "FREE-DEMO": {"plan": "free", "active": True},
    "FOUNDER-PRO": {"plan": "pro", "active": True},
    "STUDIO-ALPHA": {"plan": "studio", "active": True},
}

class VerifyLicenseRequest(BaseModel):
    license_key: str
    roblox_user_id: str | None = None
    plugin_version: str | None = None

class GenerateObbyRequest(BaseModel):
    license_key: str
    theme: str = "Cyber"
    stages: int = 50
    difficulty: str = "medium"

@app.get("/health")
def health():
    return {
        "ok": True,
        "service": "game-factory-saas",
        "time": datetime.now(timezone.utc).isoformat(),
    }

@app.post("/api/license/verify")
def verify_license(req: VerifyLicenseRequest):
    license_data = LICENSES.get(req.license_key)

    if not license_data or not license_data["active"]:
        return {
            "valid": False,
            "plan": "free",
            "features": PLANS["free"],
        }

    plan = license_data["plan"]

    return {
        "valid": True,
        "plan": plan,
        "features": PLANS[plan],
    }

@app.post("/api/generate/obby")
def generate_obby(req: GenerateObbyRequest):
    license_data = LICENSES.get(req.license_key)

    if not license_data or not license_data["active"]:
        raise HTTPException(status_code=403, detail="Invalid license")

    plan = license_data["plan"]
    features = PLANS[plan]

    if req.stages > features["stage_limit"]:
        raise HTTPException(
            status_code=403,
            detail=f"{plan} plan allows max {features['stage_limit']} stages",
        )

    if req.theme not in features["themes"]:
        raise HTTPException(
            status_code=403,
            detail=f"Theme '{req.theme}' not available on {plan} plan",
        )

    lua = f'''
-- Generated by Game Factory AI
-- Plan: {plan}
-- Theme: {req.theme}
-- Stages: {req.stages}
-- Difficulty: {req.difficulty}

local folder = Instance.new("Folder")
folder.Name = "GF_Generated_Obby_{req.theme}_{req.stages}"
folder.Parent = workspace

for i = 1, {req.stages} do
    local p = Instance.new("Part")
    p.Name = "Stage_" .. i
    p.Size = Vector3.new(14, 1, 14)
    p.Position = Vector3.new((i % 2 == 0 and 18 or -18), 5 + math.floor(i/8), i * 30)
    p.Anchored = true
    p.Material = Enum.Material.Neon
    p.Color = Color3.fromRGB(0, 255, 200)
    p.Parent = folder
end

print("Game Factory generated obby loaded.")
'''

    return {
        "ok": True,
        "plan": plan,
        "lua": lua,
    }
