
-- AUTO-GENERATED by config_bus.py — DO NOT EDIT MANUALLY
local Config = {
    Difficulty        = 2.010,
    Length            = 50,
    PlatformGap       = 3.99,
    HazardChance      = 0.800,
    CheckpointSpacing = 8,
    GameType          = "SIMULATOR",
    Monetization      = 1.403,
}
return Config
